"""add foreign keys and relationships

Revision ID: 9547d96a2510
Revises: 87cca538479e
Create Date: 2026-04-13 16:32:01.298241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9547d96a2510'
down_revision: Union[str, Sequence[str], None] = '87cca538479e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'prices', 'dumplings', ['dumpling_id'], ['id'])
    op.create_foreign_key(None, 'prices', 'shops', ['shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prices', type_='foreignkey')
    op.drop_constraint(None, 'prices', type_='foreignkey')
    # ### end Alembic commands ###
